Create 06-code-of-conduct.md
capsule-corp-ternoa/ternoa-doc pull request #84
Opened 2022-11-12 23:42 UTC by Balianos

2022-11-15 12:04 UTC, M2613 requested changes

2022-11-17 02:12 UTC, Balianos commented on docs/general/06-code-of-conduct.md
> +info@mystenlabs.com
Un oubli, dsl

2022-11-17 02:17 UTC, Balianos reviewed
Updated

2022-11-29 23:56 UTC, Balianos commented on docs/general/06-code-of-conduct.md
> +support@ternoa.com
@M2613 Done

2022-12-04 22:21 UTC, Balianos commented
@M2613 I think we're good and we can merge this =)

2022-12-08 09:18 UTC, M2613 approved these changes

2022-12-08 09:18 UTC, merged